### ISSUE TITLE
pagintation.links() does not work

### ISSUE THREAD

**Issue by njoannin** [lixxu/flask-paginate#30]
I'm having a problem with pagination.links, which is not outputting any links.

I've added pagination.links() to my view to see what the output was, but that raised an error:

```
Traceback (most recent call last):
  File "/Users/Nicolas/myproject/flask/lib/python3.3/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/Nicolas/myproject/flask/lib/python3.3/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/Nicolas/myproject/flask/lib/python3.3/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Nicolas/myproject/flask/lib/python3.3/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/Nicolas/myproject/flask/lib/python3.3/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Nicolas/myproject/flask/lib/python3.3/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Nicolas/myproject/flask/lib/python3.3/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Nicolas/myproject/flask/lib/python3.3/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/Nicolas/myproject/flask/lib/python3.3/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Nicolas/myproject/flask/lib/python3.3/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Nicolas/myproject/flask/lib/python3.3/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/Nicolas/myproject/app/util/__init__.py", line 22, in decorated_function
    return func(*args, **kwargs)
  File "/Users/Nicolas/myproject/app/lab/views.py", line 206, in inventory
    pagination.links()
  File "/Users/Nicolas/myproject/flask/lib/python3.3/site-packages/flask_paginate/__init__.py", line 356, in links
    s.append(self.single_page(page) if page else self.gap_marker_fmt)
  File "/Users/Nicolas/myproject/flask/lib/python3.3/site-packages/flask_paginate/__init__.py", line 330, in single_page
    return LINK.format(self.page_href(page), page)
  File "/Users/Nicolas/myproject/flask/lib/python3.3/site-packages/flask_paginate/__init__.py", line 202, in page_href
    return url.decode('utf8')
AttributeError: 'str' object has no attribute 'decode'
```

Changing ```
return url.decode('utf8')``` to ```
return url```
 fixes the problem.

I'm working with Python 3.3, flask-paginate 0.3.0.

**Comment by lixxu** [comment]
pagination.links is property, not method

**Comment by njoannin** [comment]
@lixxu Thanks for your reply. Indeed, that is the case.

Nevertheless, ```pagination.links``` outputs exactly the same error message.
And the modification I made (removing the ```.decode('utf8')``` fixes the problem.

Could this be an issue between Python 2 and 3?

**Comment by lixxu** [comment]
Please try the latest version, it should fix the issue.

**Comment by njoannin** [comment]
OK, thanks!
